+---------------------------+--------------+--------------+---------------------------+----------------------+--------+------------------------------------------+--------------+--------------+
|         TIMESTAMP         |    EXEC_ID   |   TRANS_ID   |          FUNCTION         |         FILE         |  LINE  |                  MESSAGE                 |   PROC_TYPE  |    STATUS    |
+---------------------------+--------------+--------------+---------------------------+----------------------+--------+------------------------------------------+--------------+--------------+
| 2025-10-12 20:26:56       | 34           | N/A          | enviaremail               | gmailService.py      | 108    | Falha ao enviar email: [Errno 11001]     | system       | failure      |
|                           |              |              |                           |                      |        | getaddrinfo failed                       |              |              |
| 2025-10-12 20:26:57       | 34           | N/A          | main                      | main.py              | 12     | ExecutionID: 34 - Process: FIN001_V3 -   | system       | information  |
|                           |              |              |                           |                      |        | Status: STARTING                         |              |              |
| 2025-10-12 20:26:58       | 34           | 11           | main                      | main.py              | 24     | Item Data: 11                            | system       | information  |
| 2025-10-12 20:26:59       | 34           | 11           | main                      | main.py              | 29     | Uso do Item dentro do try                | system       | information  |
| 2025-10-12 20:27:00       | 34           | N/A          | enviaremail               | gmailService.py      | 108    | Falha ao enviar email: [Errno 11001]     | system       | failure      |
|                           |              |              |                           |                      |        | getaddrinfo failed                       |              |              |
| 2025-10-12 20:27:00       | 34           | N/A          | main                      | main.py              | 48     | ExecutionID: 34 - Process: FIN001_V3 -   | system       | information  |
|                           |              |              |                           |                      |        | Status: SUCCESS                          |              |              |
| 2025-10-12 20:27:00       | 34           | N/A          | main                      | main.py              | 55     | ExecutionID: 34 - Process: FIN001_V3 -   | system       | information  |
|                           |              |              |                           |                      |        | Status: FINISHED                         |              |              |
+---------------------------+--------------+--------------+---------------------------+----------------------+--------+------------------------------------------+--------------+--------------+
